config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/mysidekiq'
  resources :properties
  root to: 'properties#index'
  # get 'lightbox', to:'properties#lightbox'

  resources :blogs

  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "My Contact Form",
      :to => "krec.kiran@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end

end

app/models/property.rb
class Property < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :content)
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    respond_to do |format|
      if @contact.deliver
        format.html { redirect_to root_path, notice: 'Thank you for your message. We will contact you soon!' }
      else
        flash.now[:notice] = 'Could not send the message'
      end
    end
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController

  def index

    # @properties = Property.paginate(page: params[:page], per_page: 10)

    @commercial_properties = ["Cafes & Restaurants", "Dance Studios", "Hotels" ]

    @props = ["Commercial", "External", "Industrial","Public Buildings", "Residential", "Sports facilities",
              "Studios", "Vehicles"]


    if params[:category].blank?
      @properties = Property.order("id ASC").all
    else
      @properties = Property.where(category:params["category"]).order("id ASC").all
    end

  end

  def show
    @properties = Property.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/blogs/_form.html.erb
<%= form_for(blog) do |f| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.content %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @blog.content %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/contacts/create.html.erb
<div>
  <% flash.each do |key, value| %>
    <div>
      <a href="#" data-dismiss="alert">×</a>
        <%= value %>
    </div>
  <% end %>
</div>

app/views/contacts/new.html.erb
 <div class="container placement">
  <div class="row">
    <div class="col-md-6">
       <h3 class="text-left">Get in touch</h3>
         <br>
          <%= form_for @contact do |f| %>
          <strong>Name:</strong><%= f.text_field :name, class: "form-control" %>
          <strong>Email:</strong><%= f.email_field :email, class: "form-control" %>
          <strong>Message:</strong><%= f.text_area :message, size: "40x8", class: "form-control" %>
        </br>
        <div>
          <%= f.submit "Submit" , class: " btn btn-primary form-control" %>
        </div>
         <% end %>
       </br>
     </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

  <!-- <nav class="navbar navbar-light bg-faded">
  <h1 class="navbar-brand mb-0">Location Finder</h1>
  </nav> -->

    <title>Location Finder</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

     <link href = "https://code.jquery.com/ui/1.10.4/themes/ui-lightness/jquery-ui.css" rel = "stylesheet">
      <script src = "https://code.jquery.com/jquery-1.10.2.js"></script>
      <script src = "https://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

  </head>

  <body>


   <%= yield %>
 </body>
</html>

app/views/properties/_grid.html.erb
<!-- * code for Grid view -->

<div class="col-sm-9">
  <div class="row">
    <% @properties.each do |property| %>
      <% if property[:pic].blank? %>
          <div class="col-sm-3">
          <a href="<%=property_path(property) %>">
            <%= image_tag "http://placehold.it/600x400", class: "play" %>
          </div>
        <% else %>
          <div class="col-sm-3">
           <a href="<%=property_path(property) %>">
            <%= image_tag property.pic, class: "play" %>
          </div>
        <% end %>
    <% end %>
  </div>
</div>

app/views/properties/_header.html.erb
<!-- <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
          <div class="panel panel-default">
             <div class="panel-heading"><h2><%= @properties.name %></h2></div>
          </div>
      </div>
    </div>
</div>
 -->
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading"><h2><%= @properties.name %></h2>
            </div>
         </div>
    </div>
</div>

app/views/properties/_list.html.erb
<!-- * code for List view -->

<div class="col-sm-8">
       <!--  <% if params[:category] %>
            <% @myproperties = Property.where(category:params["category"]).order("id ASC").all %>
        <% end %> -->

    <% @properties.each do |property| %>
      <% if property[:pic].blank? %>
        <div class="row">
          <a href="<%=property_path(property) %>">
            <%= image_tag "http://placehold.it/600x400", class: "play" %>
          </div>
        <% else %>
          <div class="row">
          <a href="<%=property_path(property) %>">
            <%= image_tag property.pic, class: "play" %>
          </div>
        <% end %>
    <% end %>
    </div>

app/views/properties/_sidepanel.html.erb
<!-- Side Panel code -->

<h1 class="form-group"></h1>
  <div class="row">
    <div class="col-sm-3">
    <div class="single">
        <h3><a  href="properties" class="deco-none" >Category</a></h3>
           <% @props.each do | p | %>
            <% if p == "Public Buildings" %>
                <ul class="list-unstyled">
                  <li><a href="properties?category=<%= p %>" class="deco-none" data-toggle="collapse" data-target="#commercials">Public Buildings</a>
                    <ul class="collapse" id=commercials>
                      <li><a href="http://www.google.com" class="deco-none form-group">Hotels</a></li>
                      <li><a href="" class="deco-none form-group">Clubs</a></li>
                      <li><a href="" class="deco-none form-group">Studios</a></li>
                    </ul>
                  </li>
                </ul>
              <% else %>
               <ul class="list-unstyled">
                  <li><a href= "properties?category=<%= p %>" class="deco-none" ><%= p %></a></li>
                </ul>
              <% end %>
            <% end %>
        <hr class="marker">
        <h3>Location features</h3>
          <div>
            <%= check_box_tag(:Bedrooms) %>
            <%= label_tag(:Bedroom,"Bedroom(s)")%>
          </div>
          <div>
            <%= check_box_tag(:LivingRooms) %>
            <%= label_tag(:LivingRooms,"Living room(s)") %>
          </div>
          <div>
            <%= check_box_tag(:Kitchen) %>
            <%= label_tag(:Kitchen,"Kitchen(s)") %>
          </div>
          <div>
            <%= check_box_tag(:Bathrooms) %>
            <%= label_tag(:Bathrooms,"Bathroom(s)") %>
          </div>
        <hr class="marker">
        <h3>Privacy</h3>
          <div>
            <%= check_box_tag(:low) %>
            <%= label_tag(:low,"Low") %>
          </div>
          <div>
            <%= check_box_tag(:medium) %>
            <%= label_tag(:medium,"Medium") %>
          </div>
          <div>
            <%= check_box_tag(:high) %>
            <%= label_tag(:high,"High") %>
          </div>
        <div class="update-button">
        <button type="button" class="btn btn-primary">Update view</button>
        </div>
  </div>
</div>

app/views/properties/index.html.erb
<div class="jumbotron ">
      <div class="center">
          <h1 class="display-3">Location Finder</h1>
          <p class="lead">Digital Platform to find shooting locations in London</p>
          <hr class="marker">
      </div>

     <% if notice %>
        <div class="alert alert-success alert-dismissable">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <%= notice%>
        </div>
      <% end %>

        <div class="row" >
        <div class="col-md-12">
          <a href="?view=list" class="glypicon-pos btn btn-primary btn-md pull-right">
            <span class="glyphicon glyphicon-th-list"></span> List
          </a>
          <a href="?view=grid" class="glypicon-pos btn btn-primary btn-md pull-right">
            <span class="glyphicon glyphicon-th-large"></span> Grid
          </a>
        </div>
       </div>



            <%= render 'sidepanel' %>
            <% if params[:view]=="list" %>
              <%= render 'list', properties: @properties %>
            <% else %>
              <%= render 'grid', properties: @properties %>
            <% end %>
</div>

app/views/properties/lightbox.html.erb
<!DOCTYPE html>
<html>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
  font-family: Verdana, sans-serif;
  margin: 0;
}

* {
  box-sizing: border-box;
}

.row > .column {
  padding: 0 8px;
}

.row:after {
  content: "";
  display: table;
  clear: both;
}

.column {
  float: left;
  width: 25%;
}

/* The Modal (background) */
.modal {
  display: none;
  position: fixed;
  z-index: 1;
  padding-top: 100px;
  left: 0;
  top: 0;
  width: 100%;
  height: 100%;
  overflow: auto;
  background-color: black;
}

/* Modal Content */
.modal-content {
  position: relative;
  background-color: #fefefe;
  margin: auto;
  padding: 0;
  width: 90%;
  max-width: 1200px;
}

/* The Close Button */
.close {
  color: white;
  position: absolute;
  top: 10px;
  right: 25px;
  font-size: 35px;
  font-weight: bold;
}

.close:hover,
.close:focus {
  color: #999;
  text-decoration: none;
  cursor: pointer;
}

.mySlides {
  display: none;
}

.cursor {
  cursor: pointer
}

/* Next & previous buttons */
.prev,
.next {
  cursor: pointer;
  position: absolute;
  top: 40%;
  width: auto;
  padding: 16px;
  margin-top: -50px;
  color: white;
  font-weight: bold;
  font-size: 20px;
  transition: 0.6s ease;
  border-radius: 0 3px 3px 0;
  user-select: none;
  -webkit-user-select: none;
}

/* Position the "next button" to the right */
.next {
  left:650px;
  border-radius: 3px 0 0 3px;

}

/* On hover, add a black background color with a little bit see-through */
.prev:hover,
.next:hover {
  background-color: rgba(0, 0, 0, 0.8);
}

/* Number text (1/3 etc) */
.numbertext {
  color: #f2f2f2;
  font-size: 12px;
  padding: 8px 12px;
  position: absolute;
  top: 0;
}

img {
  margin-bottom: -4px;
}

.caption-container {
  text-align: center;
  background-color: black;
  padding: 2px 16px;
  color: white;
}

.demo {
  opacity: 0.6;
}

.active,
.demo:hover {
  opacity: 1;
}

img.hover-shadow {
  transition: 0.3s
}

.hover-shadow:hover {
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19)
}

.bottom-box{

 padding-top: 10px;

}

.pic-distance{
}

</style>
<body>

<h2 style="text-align:center">Carousel</h1>



<div class="row">
<div class="column">

    <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
    <a class="next" onclick="plusSlides(1)">&#10095;</a>

    <div class="mySlides">
      <img src="http://antonyz.com/wp-content/uploads/2014/11/London-England-Tower-Bridge-Night-car-Lights.jpg" style="width:200%">
    </div>

    <div class="mySlides">
      <div class="numbertext"></div>
      <img src="http://www.thetimes.co.uk/travel/s3/growthtravel-prod/uploads/2016/04/Rome-on-a-budget.jpg" style="width:200%">
    </div>

    <div class="mySlides">
      <div class="numbertext"></div>
      <img src="http://www.zapphyre.com/wp-content/uploads/2016/03/Berlin2.jpg" style="width:200%">
    </div>

    <div class="mySlides">
      <div class="numbertext"></div>
      <img src="https://i.blogs.es/ff4749/berlin/original.jpg" style="width:200%">
    </div>


   <div class="bottom-box">

    <div class="column">
      <img class="demo" src="http://antonyz.com/wp-content/uploads/2014/11/London-England-Tower-Bridge-Night-car-Lights.jpg" style="width:100%" onclick="currentSlide(1)" >
    </div>

    <div class="column">
      <img class="demo" src="http://www.thetimes.co.uk/travel/s3/growthtravel-prod/uploads/2016/04/Rome-on-a-budget.jpg" style="width:100%" onclick="currentSlide(2)" >
    </div>

    <div class="column">
      <img class="demo" src="http://www.zapphyre.com/wp-content/uploads/2016/03/Berlin2.jpg" style="width:100%" onclick="currentSlide(3)" >
    </div>

    <div class="column">
      <img class="demo" src="https://i.blogs.es/ff4749/berlin/original.jpg" style="width:100%" onclick="currentSlide(4)">
    </div>

    </div>

  </div>
</div>

<script>
function openModal() {
  document.getElementById('myModal').style.display = "block";
}

function closeModal() {
  document.getElementById('myModal').style.display = "none";
}

var slideIndex = 1;
showSlides(slideIndex);

function plusSlides(n) {
  showSlides(slideIndex += n);
}

function currentSlide(n) {
  showSlides(slideIndex = n);
}

function showSlides(n) {
  var i;
  var slides = document.getElementsByClassName("mySlides");
  var dots = document.getElementsByClassName("demo");
  var captionText = document.getElementById("caption");
  if (n > slides.length) {slideIndex = 1}
  if (n < 1) {slideIndex = slides.length}
  for (i = 0; i < slides.length; i++) {
      slides[i].style.display = "none";
  }
  for (i = 0; i < dots.length; i++) {
      dots[i].className = dots[i].className.replace(" active", "");
  }
  slides[slideIndex-1].style.display = "block";
  dots[slideIndex-1].className += " active";
  captionText.innerHTML = dots[slideIndex-1].alt;
}
</script>

</body>
</html>

app/views/properties/show.html.erb
<%= render 'header' %>

<div class="container">
<div class="container showpage" >
  <!-- <div class="panel panel-default">
    <div class="panel-heading"><h2><%= @properties.name %></h2></div>
  </div> -->


<div class="row">
    <div class="col-sm-8">
        <div class="col-sm-12">
           <!-- <div class="row">
             <% if @properties.pic.present? %>
                <%= image_tag @properties.pic  , class: "picture"  %>
             <% end %>
           </div> -->

            <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
            <a class="next" onclick="plusSlides(1)">&#10095;</a>

<!-- Light box implementation -->

            <div class="row">
               <div class="mySlides">
                  <img src="http://antonyz.com/wp-content/uploads/2014/11/London-England-Tower-Bridge-Night-car-Lights.jpg" style="width:100%", class="play-show">
                </div>

                <div class="mySlides">
                  <div class="numbertext"></div>
                  <img src="http://www.thetimes.co.uk/travel/s3/growthtravel-prod/uploads/2016/04/Rome-on-a-budget.jpg" style="width:100%", class="play-show">
                </div>

                <div class="mySlides">
                  <div class="numbertext"></div>
                  <img src="http://www.zapphyre.com/wp-content/uploads/2016/03/Berlin2.jpg" style="width:100%", class="play-show" >
                </div>

              <div class="mySlides">
                <div class="numbertext"></div>
                <img src="https://i.blogs.es/ff4749/berlin/original.jpg" style="width:100%", class="play-show">
              </div>

              <div class="mySlides">
                  <div class="numbertext"></div>
                  <img src="http://www.zapphyre.com/wp-content/uploads/2016/03/Berlin2.jpg" style="width:100%", class="play-show" >
                </div>

              <div class="mySlides">
                <div class="numbertext"></div>
                <img src="https://i.blogs.es/ff4749/berlin/original.jpg" style="width:100%", class="play-show">
              </div>

            </div>

              <div class="row">
                      <div class="column">
                        <img class="demo" src="http://antonyz.com/wp-content/uploads/2014/11/London-England-Tower-Bridge-Night-car-Lights.jpg" style="width:100%" onclick="currentSlide(1)" >
                      </div>

                      <div class="column">
                        <img class="demo" src="http://www.thetimes.co.uk/travel/s3/growthtravel-prod/uploads/2016/04/Rome-on-a-budget.jpg" style="width:100%" onclick="currentSlide(2)" >
                      </div>

                      <div class="column">
                        <img class="demo" src="http://www.zapphyre.com/wp-content/uploads/2016/03/Berlin2.jpg" style="width:100%" onclick="currentSlide(3)" >
                      </div>

                      <div class="column">
                        <img class="demo" src="https://i.blogs.es/ff4749/berlin/original.jpg" style="width:100%" onclick="currentSlide(4)">
                      </div>
              </div>


<!--  Light box implementation end -->

           <div class="row text-area">
             <% if @properties.info.present? %>
                <%= text_area_tag 'description', @properties.info,  size: "100x8", disabled: true %>
             <% end %>
            </div>

         </div>
    </div>

    <div class="cl-sm-4 sideheading">

        <div class="row">
          <% if @properties.price %>
            <%= @properties.price %>&nbsp;per day
          <% end %>
        </div>

        <div class="row form-group date-place">
          From: <input type="text" placeholder="mm/dd/yyyy" id="from-datepicker" class="form-control">
        </div>
        <div class="row form-group date-place">
          To: <input type="text" placeholder="mm/dd/yyyy" id="to-datepicker" class="form-control">
        </div>

        <div class="row">
         <button type="button" class="btn btn-primary btn-block">Request Booking</button>
        </div>

        <div class="row form-inline ">
            <% if @properties[:pic].blank? %>
              <div class="col-sm-6 mugshot">
                  <%= image_tag "https://www.barfoot.co.nz/images/noprofile-big.png", class: "mugshot" %>
              </div>
              <% else %>
              <div class="col-sm-6 mugshot">
                  <%= image_tag "https://www.barfoot.co.nz/images/noprofile-big.png", class: "mugshot" %>
              </div>
            <% end %>

            <div class="col-sm-6 nameplace">
                John Doe
              <div>
                <!-- <button type="button" class="btn btn-primary form-control button-place ">Contact</button> -->
                <%=  link_to "Contact" , contacts_path, class: "btn btn-primary form-control button-place" %>

              </div>
            </div>

        </div>

      <div class="row pic_placement">
       <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2482.6476609170627!2d-0.09110564875278862!3d51.51967977953724!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x48761cabe5517883%3A0xcdad2ecccc500599!2sRopemaker+St%2C+London+EC2Y!5e0!3m2!1sen!2suk!4v1490258171937" width="300" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
      </div>

  </div>
</div>
</div>


<script type="text/javascript">
  $(document).ready(function(){
    $('#from-datepicker').datepicker();
    $('#to-datepicker').datepicker();
  });
</script>


<script>
function openModal() {
  document.getElementById('myModal').style.display = "block";
}

function closeModal() {
  document.getElementById('myModal').style.display = "none";
}

var slideIndex = 1;
showSlides(slideIndex);

function plusSlides(n) {
  showSlides(slideIndex += n);
}

function currentSlide(n) {
  showSlides(slideIndex = n);
}

function showSlides(n) {
  var i;
  var slides = document.getElementsByClassName("mySlides");
  var dots = document.getElementsByClassName("demo");
  var captionText = document.getElementById("caption");
  if (n > slides.length) {slideIndex = 1}
  if (n < 1) {slideIndex = slides.length}
  for (i = 0; i < slides.length; i++) {
      slides[i].style.display = "none";
  }
  for (i = 0; i < dots.length; i++) {
      dots[i].className = dots[i].className.replace(" active", "");
  }
  slides[slideIndex-1].style.display = "block";
  dots[slideIndex-1].className += " active";
  captionText.innerHTML = dots[slideIndex-1].alt;
}
</script>